### ISSUE TITLE
请求增加登陆成功的提示通知

### ISSUE THREAD

**Issue by debugAllTheTime** [kewuaa/uestc_wifi_helper#1]
哈哈哈哈开始push。
求大佬增加一个登陆成功后通知的功能咩？
例如发送windows通知

**Comment by kewuaa** [comment]
需要啥样的通知啊

**Comment by debugAllTheTime** [comment]
有个通知就好哈哈哈。我晚上回去试试移动可以用不

**Comment by kewuaa** [comment]
我直接更新成托盘程序了，登录成功会发Windows通知

**Comment by kewuaa** [comment]
你看看咋样

**Comment by debugAllTheTime** [comment]
好哦。我马上看。等我室友这把dota打完

**Comment by debugAllTheTime** [comment]
![Snipaste_2023-10-28_00-23-08](https://github.com/kewuaa/uestc_wifi_helper/assets/25170510/c7d8c81c-888a-4d89-a318-8e56be1d55db)
移动可以使用

**Comment by kewuaa** [comment]
ok
