### ISSUE TITLE
最新版本运行托盘程序版本运行后无提示

### ISSUE THREAD

**Issue by debugAllTheTime** [kewuaa/uestc_wifi_helper#4]
最新版本运行托盘程序版本运行后无任何响应，无提示。
也没有和我说在哪里创建配置文件。
请问一下那个用户目录就是exe文件所在目录吗？如果是的话我已经手动创建也没有弹任何提示

**Comment by kewuaa** [comment]
我去看看，因为我现在主要用的是linux, 还有用户目录是C:\Users\你的用户名

**Comment by debugAllTheTime** [comment]
搞定啦。非常感谢。我手动把配置文件放在用户目录就好了

**Comment by kewuaa** [comment]
okok,我在去找找问题
